#!/bin/sh
### BEGIN INIT INFO
# Provides:          bt
# Required-Start:    $remote_fs $syslog $networking
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: bt
# Description:       bt
# Author:            Cedric Quillevere / origin@killy.net
# Rewamped	     Christian Svedin / christian.svedin@gmail.com
# Version:           1.2
### END INIT INFO
case "$1" in
start)
nohup mldonkey >/dev/null&
nohup deluged >/dev/null&
nohup deluge-web >/dev/null&
;;
stop)
 kill -9 $(pidof deluged)
;;
restart)
 kill -9 $(pidof deluged)& nohup deluged&
esac
